# Generated by Django 4.2.1 on 2023-05-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='车辆编号')),
                ('carpinpai', models.CharField(max_length=125, verbose_name='车辆品牌')),
                ('carname', models.CharField(max_length=125, verbose_name='车辆名字')),
                ('carprice', models.CharField(max_length=125, null=True, verbose_name='车辆价格')),
                ('carimage', models.CharField(max_length=355, null=True, verbose_name='车辆图片')),
            ],
            options={
                'db_table': 'carinfo',
            },
        ),
        migrations.CreateModel(
            name='UserInFo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户表主键')),
                ('username', models.CharField(max_length=25, verbose_name='用户姓名')),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
